"""initial schema baseline

Revision ID: 43be3a8d6b40
Revises: 
Create Date: 2026-04-30 21:56:08.549055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43be3a8d6b40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['referral_code'])
        batch_op.create_foreign_key(None, 'user', ['referred_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
